"""initial setup

Revision ID: bfecdb2be76c
Revises: 
Create Date: 2025-02-23 21:05:39.319507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfecdb2be76c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Man', 'Woman', 'Other', name='traintype'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('ethnicity', sa.Enum('White', 'Black', 'AsianAmerican', 'EastAsian', 'SouthEastAsian', 'MiddleEastern', 'Pacific', 'Hispanic', name='ethnicitytypes'), nullable=False),
    sa.Column('eyecolor', sa.Enum('Brown', 'Blue', 'Hazel', 'Green', 'Grey', name='eyecolortypes'), nullable=False),
    sa.Column('bald', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('output_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_images_created_at'), 'output_images', ['created_at'], unique=False)
    op.create_table('pack_prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_images')
    op.drop_table('pack_prompts')
    op.drop_index(op.f('ix_output_images_created_at'), table_name='output_images')
    op.drop_table('output_images')
    op.drop_table('users')
    op.drop_table('packs')
    op.drop_table('models')
    # ### end Alembic commands ###
